### ISSUE TITLE
三跨南大CS专硕上岸的一点经验（by big头）

### ISSUE THREAD

**Issue by huangzhhhhh** [ThyrixYang/nju_cs_kaoyan_19#2]
先说明个人情况，本科普通211计算机无关工科专业，初试成绩数学114，英语65，政治73，专业课108。由于复试成绩现在还没公布（分太低）就不说了。
个人认为，对于考研这件事情，尽量早准备，特别是跨专业的同学，在确定了自己的目标之后，就只要做一件事，坚持。本文下面将从考研的几个阶段和不同的课程分享一些经验。
首先，确定学校，这应该是3，4月份就要做好的工作，个人不推荐准备了一段时间后再更改目标。关于计算机考研学校，行业排名，专业评级可以参考王道论坛和教育部官网的一些数据，而对于跨专业的同学，最好弄清楚你的目标院校是否对跨专业有歧视或者不公平的现象（这一点可以看各个学校的初试复试分数比例，复试面试比例等因素，一般复试比重高，复试里边面试比重又高的要小心），不过，南京大学是不歧视跨专业的同学的，这也是我选择这里的原因之一。
下面我把考研分成了三个阶段：初期（3~6月）、中期（7~10月）、后期（11~12月）来进行讲述。（这个进度更适合跨专业考生）
初期，这个时候开始对你所要考的学校专业课进行全方位的了解并收集资料，加群问学长要，淘宝买都可以（我是直接淘宝买了，包括老师的课件，期末题，真题还有答案，直接淘宝搜南大计算机考研就行），英语基础差的同学也可以这个时候开始准备了，买单词书什么的，数学一量大，建议慢慢开始（基础好的同学可以晚一点），最晚5月也要开始了。总之，初期是一个慢慢调整自己状态的阶段，让自己慢慢的找到适合自己的作息，刚开始可以慢一点，但是不能停，一天都别停。专业课大概一个月一本书吧，可能数据结构和计算机系统基础会久一点，把课后题都做一下，可以对着前边的书做。这个阶段每天数学2小时，英语2小时，专业课2.5小时。
中期，这是一个十分关键的时间段，专业课各个科目在这段时间的上升是最大的，我简单说下我自己在这段时间做的事情吧。数学一知识点都过了一遍了，开始刷题模式，我用的汤家凤1800，难度比较大，但是计算量不算多，经常做的自己怀疑人生是很正常的，坚持住，尽量不看答案自己做，把错题和没想到方法的题圈起来，做完一遍之后多看圈的题；英语一难度也不小，我自己的英语基础差，所以我把近15年的真题里的阅读（每张卷子4篇）都通篇翻译了，翻译的时候一定要写出来，不要觉得自己好像看懂了就不写了，不然真的做翻译题的时候会很难受，然后不认识的单词记下来并背诵，同时每天看一篇作文，积累一点句子；政治在八月中旬开始吧，看徐涛的课，做一些选择题，这个就是强推徐涛了，肖秀荣的押题厉害，但讲课真的是催眠曲；专业课在这段时间就要非常认真的做题了，之前第一遍是为了对各个点有一个概念，这一遍我除了计算机系统基础之外都用的王道的练习题，因为有答案还有解析还有知识点精炼，同样的，尽量自己做，把做错了的和不会的圈起来，计算机系统基础可以买这本书的教师用书，里边还有选择题，大题和答案。这个阶段每天数学3.5小时，英语3.5小时，专业课3.5小时。（有了政治之后大概从其他各个里边抽0.5小时出来然后再加半个小时，就是2小时）
后期，这是考验人最艰难的时期，身边签工作的走了一批，放弃的走了一批（这个时间放弃的人很多很多，请坚持住），这段时间应该是所有知识性的东西都在脑子里了，可以开始刷真题了，可能一开始不太习惯845的风格，但做了一两张卷子之后就好了，因为知识其实就是那些，考查方式不一样而已，还有就是看自己之前圈的题；数学的话据说有大小年，想清楚自己的年份和水平，用真题练速度和准确性，这两点对数学来说很重要，还有就是看自己之前圈的题；英语这个时候单词量应该都没问题了，开始抓写作和新题型了，个人不推荐直接背范文，可以买王江涛的作文书，每个题目自己先写，然后和范文对照，看哪些句子自己能写出来但没想到，然后记下来，多练习写作不会差的，新题型的话各个题型最好都要练，好像并没有出题规律可言；政治的话就是刷肖四肖八了，肖四大题建议背下来（比如今年基本全中），酌情背一背徐涛的小黄书。这个阶段每天数学3小时，英语2.5小时，政治2.5小时，专业课3小时。
初试完了就是复试了，考完初试之后可以歇个两三天，整理整理自己的心情，然后就是复试准备阶段（不论初试感觉怎么样都要准备），南京大学的复试科目较多，包括编译原理、离散数学、机试、面试，其中编译离散一起考，建议没基础的同学加大工作量，先把编译原理拿下，然后啃离散，南大离散题目很难，实在不行还是先保证编译原理；机试的话如果不知道什么是dp、dfs、bfs、分治，去B站上边搜一搜先了解概念，然后上LeetCode刷题，这个OJ网站比较好，题目有英文和中文版本，题目分了类型，并从易到难有排序，而且有评论（相当于解析），建议刷到中等难度；面试的话如果本科有过相关的经历可以说一说，没有的话也不要慌，落落大方就好，老师不会为难人。
另外，在初试成绩出来之后就可以联系导师了，态度诚恳一点，谦虚一点，不要一次性联系多个，如果老师拒了你也不要灰心，再找其他的就行。复试和联系导师的阶段，信息很重要，多了解一些信息对自己会很有帮助的，建议多和学长沟通。
最后，想告诉各位考研路上的同学，考研是一场坚持到最后就是胜利的战斗，不管最终是否考上，这段经历都是很珍贵的，还有就是考前一定要调整好心态，本人考政治前一晚上失眠到3点（当时想完蛋了），最后还是去考了（毕竟报名费都交了233），在此祝各位同学考出自己的水平。

**Comment by ThyrixYang** [comment]
谢谢，已经添加到wiki
