### ISSUE TITLE
．．．．．．．．．．．．．．．

### ISSUE THREAD

**Issue by ThyrixYang** [ThyrixYang/nju_cs_kaoyan_19#6]
> 学长你好，请问心理测验都有哪些问题

大佬对自己的性生活满意吗

_Originally posted by @Gunkkk in https://github.com/ThyrixYang/nju_cs_kaoyan_19/issues/3#issuecomment-477025867_

请问不满意影响我考南大吗

**Comment by mundanePeo** [comment]
你好大佬，不影响的

**Comment by ThyrixYang** [comment]
> 你好大佬，不影响的

大兄弟你想干啥
